import type {
  ActivityLog,
  AdminProfile,
  AdminSeedData,
  DashboardWidget,
  ManagedRecord,
  ManagedUser,
  NotificationItem,
  UploadedFileItem,
} from "@/types/admin";

const now = Date.now();

function iso(minutesAgo: number) {
  return new Date(now - minutesAgo * 60_000).toISOString();
}

export const demoAdmin: AdminProfile = {
  id: "demo-super-admin",
  name: "Defne Arslan",
  email: "admin@propanel.dev",
  role: "super_admin",
  avatarUrl:
    "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80",
  lastLogin: iso(8),
  provider: "demo",
};

export const defaultWidgets: DashboardWidget[] = [
  { id: "metrics", title: "Canlı metrikler", type: "metrics", visible: true },
  { id: "sales", title: "Satış analizi", type: "sales", visible: true },
  {
    id: "active-users",
    title: "Günlük aktif kullanıcı",
    type: "active-users",
    visible: true,
  },
  { id: "system", title: "Sistem durumu", type: "system", visible: true },
  { id: "activity", title: "Son işlemler", type: "activity", visible: true },
];

export const seedUsers: ManagedUser[] = [
  {
    id: "usr_001",
    name: "Mert Yalçın",
    email: "mert@novaapp.com",
    role: "admin",
    status: "active",
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80",
    plan: "Enterprise",
    createdAt: iso(42000),
    lastActive: iso(4),
    revenue: 128400,
    location: "İstanbul",
    verified: true,
    sessions: 5,
  },
  {
    id: "usr_002",
    name: "Ece Demir",
    email: "ece@stripebox.io",
    role: "moderator",
    status: "active",
    avatarUrl:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=160&q=80",
    plan: "Business",
    createdAt: iso(32100),
    lastActive: iso(18),
    revenue: 64750,
    location: "Ankara",
    verified: true,
    sessions: 3,
  },
  {
    id: "usr_003",
    name: "Kerem Aksoy",
    email: "kerem@orbitcrm.co",
    role: "editor",
    status: "passive",
    avatarUrl:
      "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=160&q=80",
    plan: "Pro",
    createdAt: iso(12700),
    lastActive: iso(780),
    revenue: 21900,
    location: "İzmir",
    verified: false,
    sessions: 1,
  },
  {
    id: "usr_004",
    name: "Selin Koç",
    email: "selin@vergeai.app",
    role: "admin",
    status: "active",
    avatarUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=80",
    plan: "Enterprise",
    createdAt: iso(88500),
    lastActive: iso(2),
    revenue: 176000,
    location: "Berlin",
    verified: true,
    sessions: 8,
  },
  {
    id: "usr_005",
    name: "Can Ergin",
    email: "can@marketflow.dev",
    role: "editor",
    status: "banned",
    avatarUrl:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=160&q=80",
    plan: "Free",
    createdAt: iso(6500),
    lastActive: iso(3600),
    revenue: 0,
    location: "Bursa",
    verified: false,
    sessions: 0,
  },
  {
    id: "usr_006",
    name: "Lara Şahin",
    email: "lara@finpulse.ai",
    role: "moderator",
    status: "active",
    avatarUrl:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=160&q=80",
    plan: "Business",
    createdAt: iso(23800),
    lastActive: iso(33),
    revenue: 58400,
    location: "Amsterdam",
    verified: true,
    sessions: 2,
  },
];

export const seedRecords: ManagedRecord[] = [
  {
    id: "rec_1001",
    title: "Kurumsal abonelik sözleşmesi",
    owner: "Mert Yalçın",
    category: "Sales",
    status: "published",
    priority: "High",
    updatedAt: iso(20),
    amount: 184000,
    tags: ["enterprise", "renewal"],
  },
  {
    id: "rec_1002",
    title: "Q2 kampanya bütçesi",
    owner: "Ece Demir",
    category: "Finance",
    status: "draft",
    priority: "Medium",
    updatedAt: iso(74),
    amount: 42000,
    tags: ["budget", "growth"],
  },
  {
    id: "rec_1003",
    title: "Güvenlik inceleme raporu",
    owner: "Selin Koç",
    category: "Security",
    status: "published",
    priority: "High",
    updatedAt: iso(130),
    amount: 0,
    tags: ["audit", "soc2"],
  },
  {
    id: "rec_1004",
    title: "Yeni müşteri onboarding akışı",
    owner: "Lara Şahin",
    category: "Product",
    status: "published",
    priority: "Medium",
    updatedAt: iso(220),
    amount: 12800,
    tags: ["activation", "ux"],
  },
  {
    id: "rec_1005",
    title: "Arşivlenen demo verileri",
    owner: "Kerem Aksoy",
    category: "Ops",
    status: "archived",
    priority: "Low",
    updatedAt: iso(1420),
    amount: 0,
    tags: ["archive"],
  },
];

export const seedActivities: ActivityLog[] = [
  {
    id: "act_001",
    actor: "Defne Arslan",
    actorRole: "super_admin",
    action: "Rol güncelledi",
    target: "Ece Demir -> Moderator",
    level: "info",
    createdAt: iso(6),
    ip: "78.173.11.42",
  },
  {
    id: "act_002",
    actor: "Sistem",
    actorRole: "admin",
    action: "Rate limit uyarısı",
    target: "/api/session",
    level: "warning",
    createdAt: iso(21),
    ip: "10.0.0.8",
  },
  {
    id: "act_003",
    actor: "Selin Koç",
    actorRole: "admin",
    action: "PDF export aldı",
    target: "Kullanıcı tablosu",
    level: "info",
    createdAt: iso(48),
    ip: "88.249.14.90",
  },
  {
    id: "act_004",
    actor: "Güvenlik",
    actorRole: "admin",
    action: "Şüpheli oturum kapatıldı",
    target: "Can Ergin",
    level: "critical",
    createdAt: iso(120),
    ip: "185.12.0.33",
  },
];

export const seedUploads: UploadedFileItem[] = [
  {
    id: "file_001",
    name: "security-audit.pdf",
    type: "application/pdf",
    size: 1_940_000,
    status: "done",
    progress: 100,
    uploadedAt: iso(90),
    url: "#",
  },
  {
    id: "file_002",
    name: "dashboard-cover.png",
    type: "image/png",
    size: 840_000,
    status: "done",
    progress: 100,
    uploadedAt: iso(260),
    url: "#",
  },
];

export const seedNotifications: NotificationItem[] = [
  {
    id: "ntf_001",
    title: "Yeni ödeme alındı",
    message: "Enterprise plan için 184.000 TL tahsil edildi.",
    type: "success",
    read: false,
    createdAt: iso(9),
  },
  {
    id: "ntf_002",
    title: "Güvenlik uyarısı",
    message: "Can Ergin hesabında olağan dışı oturum denemesi var.",
    type: "warning",
    read: false,
    createdAt: iso(35),
  },
  {
    id: "ntf_003",
    title: "Firestore senkron",
    message: "Gerçek zamanlı veri kanalı hazır.",
    type: "info",
    read: true,
    createdAt: iso(140),
  },
];

export const seedData: AdminSeedData = {
  users: seedUsers,
  metrics: [
    {
      id: "mrr",
      label: "Aylık gelir",
      value: 842900,
      suffix: "TL",
      change: 18.4,
      trend: "up",
      description: "Son 30 gün",
    },
    {
      id: "active-users",
      label: "Aktif kullanıcı",
      value: 28430,
      change: 9.1,
      trend: "up",
      description: "Günlük aktif",
    },
    {
      id: "conversion",
      label: "Dönüşüm",
      value: 12.8,
      suffix: "%",
      change: 2.7,
      trend: "up",
      description: "Trial -> paid",
    },
    {
      id: "incidents",
      label: "Açık olay",
      value: 3,
      change: -14.2,
      trend: "down",
      description: "Sistem sağlığı",
    },
  ],
  sales: [
    { label: "Oca", revenue: 420000, users: 9800, churn: 3.2 },
    { label: "Şub", revenue: 510000, users: 11800, churn: 2.9 },
    { label: "Mar", revenue: 590000, users: 14200, churn: 2.7 },
    { label: "Nis", revenue: 710000, users: 18600, churn: 2.2 },
    { label: "May", revenue: 842900, users: 28430, churn: 1.8 },
  ],
  activeUsers: [
    { hour: "08:00", active: 2200, mobile: 1240, desktop: 960 },
    { hour: "10:00", active: 6400, mobile: 3280, desktop: 3120 },
    { hour: "12:00", active: 9200, mobile: 5100, desktop: 4100 },
    { hour: "14:00", active: 11800, mobile: 6900, desktop: 4900 },
    { hour: "16:00", active: 10400, mobile: 5900, desktop: 4500 },
    { hour: "18:00", active: 7600, mobile: 4700, desktop: 2900 },
  ],
  statuses: [
    { service: "Firestore", status: "operational", latency: 42, uptime: 99.99 },
    { service: "Auth", status: "operational", latency: 36, uptime: 99.98 },
    { service: "Storage", status: "operational", latency: 58, uptime: 99.95 },
    { service: "Export API", status: "degraded", latency: 184, uptime: 99.71 },
  ],
  activities: seedActivities,
  records: seedRecords,
  uploads: seedUploads,
  notifications: seedNotifications,
  sessions: [
    {
      id: "ses_001",
      user: "Defne Arslan",
      device: "MacBook Pro / Chrome",
      location: "İstanbul",
      ip: "78.173.11.42",
      status: "active",
      startedAt: iso(16),
    },
    {
      id: "ses_002",
      user: "Selin Koç",
      device: "iPhone / Safari",
      location: "Berlin",
      ip: "88.249.14.90",
      status: "active",
      startedAt: iso(84),
    },
    {
      id: "ses_003",
      user: "Can Ergin",
      device: "Windows / Edge",
      location: "Bursa",
      ip: "185.12.0.33",
      status: "revoked",
      startedAt: iso(140),
    },
  ],
};
