import type {
  ActivityItem,
  ChartPoint,
  NotificationItem,
  Order,
  PanelUser,
  Product,
} from "@/lib/types";

export const seedUsers: PanelUser[] = [
  {
    id: "USR-1001",
    name: "Aylin Demir",
    email: "aylin@ornekfirma.com",
    role: "Admin",
    status: "Aktif",
    joinedAt: "2026-05-08",
    orders: 18,
    spent: 42600,
  },
  {
    id: "USR-1002",
    name: "Mert Kaya",
    email: "mert@ornekfirma.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2026-05-10",
    orders: 12,
    spent: 28350,
  },
  {
    id: "USR-1003",
    name: "Selin Aras",
    email: "selin@ornekfirma.com",
    role: "Destek",
    status: "Beklemede",
    joinedAt: "2026-05-12",
    orders: 7,
    spent: 15400,
  },
  {
    id: "USR-1004",
    name: "Kerem Oz",
    email: "kerem@ornekfirma.com",
    role: "Musteri",
    status: "Aktif",
    joinedAt: "2026-05-14",
    orders: 9,
    spent: 19890,
  },
  {
    id: "USR-1005",
    name: "Ece Yilmaz",
    email: "ece@ornekfirma.com",
    role: "Musteri",
    status: "Pasif",
    joinedAt: "2026-05-16",
    orders: 4,
    spent: 7200,
  },
];

export const seedOrders: Order[] = [
  {
    id: "ORD-24091",
    customer: "Aylin Demir",
    email: "aylin@ornekfirma.com",
    product: "Premium Panel Kurulumu",
    status: "Tamamlandi",
    total: 9800,
    date: "2026-05-21",
    payment: "Kart",
    city: "Istanbul",
  },
  {
    id: "ORD-24092",
    customer: "Mert Kaya",
    email: "mert@ornekfirma.com",
    product: "E-ticaret Veri Paketi",
    status: "Hazirlaniyor",
    total: 6400,
    date: "2026-05-21",
    payment: "Havale",
    city: "Ankara",
  },
  {
    id: "ORD-24093",
    customer: "Selin Aras",
    email: "selin@ornekfirma.com",
    product: "Stok Takip Modulu",
    status: "Yeni",
    total: 4200,
    date: "2026-05-20",
    payment: "Kart",
    city: "Izmir",
  },
  {
    id: "ORD-24094",
    customer: "Kerem Oz",
    email: "kerem@ornekfirma.com",
    product: "Raporlama Paketi",
    status: "Tamamlandi",
    total: 3600,
    date: "2026-05-20",
    payment: "Kapida",
    city: "Bursa",
  },
  {
    id: "ORD-24095",
    customer: "Ece Yilmaz",
    email: "ece@ornekfirma.com",
    product: "Kullanici Yetki Paketi",
    status: "Iptal",
    total: 2800,
    date: "2026-05-19",
    payment: "Havale",
    city: "Antalya",
  },
];

export const seedProducts: Product[] = [
  {
    id: "PRD-501",
    name: "Admin Panel Lisansi",
    category: "Yazilim",
    price: 12500,
    stock: 42,
    status: "Aktif",
    sales: 128,
  },
  {
    id: "PRD-502",
    name: "Raporlama Modulu",
    category: "Modul",
    price: 5400,
    stock: 18,
    status: "Aktif",
    sales: 76,
  },
  {
    id: "PRD-503",
    name: "Bildirim Servisi",
    category: "Servis",
    price: 3200,
    stock: 9,
    status: "Aktif",
    sales: 45,
  },
  {
    id: "PRD-504",
    name: "Stok Takip Eklentisi",
    category: "Modul",
    price: 4200,
    stock: 0,
    status: "Stokta Yok",
    sales: 39,
  },
  {
    id: "PRD-505",
    name: "Kurumsal Tema Seti",
    category: "Tasarim",
    price: 2600,
    stock: 24,
    status: "Taslak",
    sales: 21,
  },
];

export const seedNotifications: NotificationItem[] = [
  {
    id: "NTF-1",
    title: "Yeni siparis alindi",
    description: "Selin Aras stok takip modulu icin siparis olusturdu.",
    type: "order",
    read: false,
    createdAt: "Bugun, 15:42",
  },
  {
    id: "NTF-2",
    title: "Sistem bakimi tamamlandi",
    description: "Firestore indeksleri ve panel cache yenilemesi basarili.",
    type: "system",
    read: false,
    createdAt: "Bugun, 13:10",
  },
  {
    id: "NTF-3",
    title: "Stok uyarisi",
    description: "Bildirim servisi stok seviyesi kritik esige yaklasti.",
    type: "stock",
    read: true,
    createdAt: "Dun, 18:25",
  },
  {
    id: "NTF-4",
    title: "Yeni kullanici eklendi",
    description: "Destek ekibine yeni bir kullanici davet edildi.",
    type: "user",
    read: true,
    createdAt: "Dun, 10:04",
  },
];

export const seedActivities: ActivityItem[] = [
  {
    id: "ACT-1",
    title: "Siparis durumu guncellendi",
    detail: "ORD-24092 hazirlaniyor durumuna tasindi.",
    createdAt: "8 dk once",
    tone: "cyan",
  },
  {
    id: "ACT-2",
    title: "Yeni urun taslagi",
    detail: "Kurumsal tema seti taslak olarak kaydedildi.",
    createdAt: "28 dk once",
    tone: "amber",
  },
  {
    id: "ACT-3",
    title: "Odeme onaylandi",
    detail: "Premium panel kurulumu icin kart odemesi basarili.",
    createdAt: "1 sa once",
    tone: "emerald",
  },
  {
    id: "ACT-4",
    title: "Siparis iptal edildi",
    detail: "ORD-24095 musteri talebiyle iptal edildi.",
    createdAt: "3 sa once",
    tone: "rose",
  },
];

export const revenueChart: ChartPoint[] = [
  { label: "Pzt", value: 14200 },
  { label: "Sal", value: 18900 },
  { label: "Car", value: 15800 },
  { label: "Per", value: 22100 },
  { label: "Cum", value: 26400 },
  { label: "Cmt", value: 17800 },
  { label: "Paz", value: 20300 },
];

export const userGrowthChart: ChartPoint[] = [
  { label: "Oca", value: 120 },
  { label: "Sub", value: 146 },
  { label: "Mar", value: 162 },
  { label: "Nis", value: 214 },
  { label: "May", value: 268 },
  { label: "Haz", value: 312 },
];
